version: '3.8'  # Specify the Docker Compose version

services:
  database:
    image: mysql:5.7  # Use MySQL version 5.7
    container_name: database  # Name for the database container
    volumes:
      - mysql-data:/var/lib/mysql  # Named volume for persistent MySQL data
    networks:
      - wedding  # Connect to the wedding network
    environment:
      MYSQL_DATABASE: rsvp  # Database name to create
      MYSQL_ROOT_PASSWORD: kali  # Root password for MySQL
    ports:
      - "3306:3306"  # Map port 3306 to the host
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

  flaskapp:
    build:   # Build the Flask app using the Dockerfile in the current directory
     context: .
    image: wedding
    container_name: flaskapp  # Name for the Flask app container
    networks:
      - wedding  # Connect to the wedding network
    environment:
      MYSQL_HOST: database  # Hostname of the MySQL container
      MYSQL_USER: root  # MySQL user
      MYSQL_PASSWORD: kali  # MySQL password
      MYSQL_DB: rsvp  # Database name
    ports:
      - "5000:5000"  # Map port 5000 to the host
    depends_on:
      database:
        condition: service_healthy

networks:
  wedding:  # Define the wedding network

volumes:
  mysql-data:  # Define the named volume for MySQL data persistence
