apiVersion: v1
kind: PersistentVolume
metadata:
 name: mysql-pv
spec:
 capacity:
   storage: 100Mi
 volumeMode: Filesystem
 accessModes:
  - ReadWriteOnce
 persistentVolumeReclaimPolicy: Retain
 hostPath:
<<<<<<< HEAD
   path: /home/ubuntu/Wedding/mysqldata
=======
   path: /home/pro-ubuntu/Wedding-lite/mysqldata
>>>>>>> ec69ccc (wedding)
