apiVersion: v1
kind: PersistentVolume
metadata:
 name: mysql-pv
spec:
 capacity:
   storage: 100Mi
 volumeMode: Filesystem
 accessModes:
  - ReadWriteOnce
 persistentVolumeReclaimPolicy: Retain
 hostPath:
   path: /home/ubuntu/workspace/Wedding/mysqldata
