apiVersion: v1
kind: Pod
metadata:
 name: wedding-pod

spec:
 containers:
  - name: wedding
    image: bakhtawar375/wedding:latest
    env:
      - name: MYSQL_HOST
        value: "database"         # This Is Your MYSQL Service Name Or IP 
      - name: MYSQL_USER
        value: "root"
      - name: MYSQL_PASSWORD 
        value: "kali"
      - name: MYSQL_DB
        value: "rsvp"

    ports:
      - containerPort: 5000
    imagePullPolicy: Always 
